### ISSUE TITLE
Selectively activate hook for keyboard only (and not mouse)

### ISSUE THREAD

**Issue by Indigo744** [AgentFire/AgentFire.Input.Hooks#1]
Hello,

Thank you for this very nice lib. It works really well!

I do have a question though: my app only need the Keyboard hook (I only set the `KeyEvent` handler), so I was wondering if it would be possible to provide a way to not hook the mouse?

For instance, it would be a [parameter for the `HardwareHook()` constructor](https://github.com/AgentFire/AgentFire.Input.Hooks/blob/6d3e992e8fe126cbaaea87234181a7f8294a2df2/AgentFire.Input.Hooks/HardwareHook.cs#L242)?

What do you think? I can try to provide a PR if you want.

Thank you for your consideration 😸

**Comment by Indigo744** [comment]
As a workaround, and to avoid annoying you with my request, I am considering forking your repo and providing an alternative nuget package with a `KeyboardHook` class (offering only the keyboard hook and removing all mouse-related code).

However, no explicit licence are provided, so I don't know if I have the right to do so... Or if you would actually approve this.

I would love to have your feedback on this.

Thank you! Have a nice day.

**Comment by Indigo744** [comment]
While waiting for a proper answer, here is my workaround/hack using reflection:
```cs
private void UnhookMouseHardwareHook(HardwareHook hook)
{
    var privMouseHookIdField = typeof(HardwareHook).GetField("_mouseHookId", BindingFlags.NonPublic | BindingFlags.Instance);
    var privMouseHookIdRaw = privMouseHookIdField?.GetValue(hook);
    if (privMouseHookIdRaw is IntPtr privMouseHookId && privMouseHookId != IntPtr.Zero)
    {
        UnhookWindowsHookEx(privMouseHookId);
    }
}

[DllImport("user32.dll", CharSet = CharSet.Auto, SetLastError = true)]
[return: MarshalAs(UnmanagedType.Bool)]
internal static extern bool UnhookWindowsHookEx(IntPtr hhk);
```

Simply call `UnhookMouseHardwareHook(_hook)` after creating the `HardwareHook` object.

**Comment by AgentFire** [comment]
Ok, first, thanks @Indigo744 for your interest in the lib.
Second, I'm sorry for the late reply, as I have poor notification settings and didn't see the issue you've created.
Finally, sure, I'll make it more versatile as you've quite accurately suggested.

**Comment by Indigo744** [comment]
Thank you for your reply! This lib is really nice and I was glad to stumble upon it.

It helped me a lot to understand how to do this in C#/.Net.

In the end, I created my own class in my project because I also needed to access the [`LLKHF_INJECTED` flag from the `KBDLLHOOKSTRUCT`](https://learn.microsoft.com/fr-fr/windows/win32/api/winuser/ns-winuser-kbdllhookstruct?redirectedfrom=MSDN).

If you're interested, here is the code I added:
```cs
/* Some constants / structs */
private const int LLKHF_INJECTED = 0x10;
private struct KBDLLHOOKSTRUCT
{
    public int vkCode;
    public int scanCode;
    public int flags;
    public int time;
    public UIntPtr dwExtraInfo;
}


/* And inside HookCallback(), after IsKeyboardEvent(wParam) */

var kbdLlHook = Marshal.PtrToStructure<KBDLLHOOKSTRUCT>(lParam);
var isInjected = (kbdLlHook.flags & LLKHF_INJECTED) != 0;
// ...
RawKeyEventArgs args = new RawKeyEventArgs(key, wasPressed, isInjected); // isInjected is a new property in the RawKeyEventArgs class
```

If you want, I can provide a PR. Just let me know.

**Comment by AgentFire** [comment]
I'm upgrading .csproj and beautifying .cs files somewhat at the moment, as well as separating kbd from mouse hooks, so i'll just go ahead and add some key event metadata with your input of `isInjected`. Thinking of adding some desktop-based test project as well.

Will post a new nuget as soon as everything is done, might take a day or two tho.

**Comment by Indigo744** [comment]
Thanks a lot! No sweat, take your time of course 😸

**Comment by AgentFire** [comment]
Ok you can try it out now, before I'll be releasing the nuget.

**Comment by Indigo744** [comment]
Nice! I see you modified quite a lot of things 😺 

It would be good to update the README.md in order to reflect all the changes.

Since you're now checking for `HookFlags.Injected`, would it be possible to also surface the other flags? Like `HookFlags.Extended` and `HookFlags.AltDown`.

**Comment by AgentFire** [comment]
If you want to know whether the Alt (or any other modifier-) key is down, you should just observe for them in the regular callback method.

**Comment by Indigo744** [comment]
Alright! I'm closing this issue then, thanks a lot 😸
